version: '3'

services:

  redis:
    image: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=ghjcnjq77
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d habitos" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: sh -c "python3 manage.py makemigrations ; \
                    python3 manage.py migrate ; \ 
                    python3 manage.py loaddata /code/data/*.json ; \
                    python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "python3 manage.py shell" ]
      interval: 10s
      timeout: 5s
      retries: 5

  celery_worker:
    build: .
    env_file: .env
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      app:
        condition: service_healthy

  celery_beat:
    build: .
    env_file: .env
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      app:
        condition: service_healthy
      celery_worker:
        condition: service_started

volumes:
  pg_data: