# Generated by Django 4.2.8 on 2023-12-26 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_estimated_time_alter_habit_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_action_datetime',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name='Last Action'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Frequency (days)'),
        ),
    ]
